### ISSUE TITLE
[Request] Please add your app in this list of good opensource android apps

### ISSUE THREAD

**Issue by pitsi** [evait-security/android-wifi-key-view#9]
I found your app a few days ago from a reddit post on r/androidapps. I installed it on my rooted device and I am really happy with it. Thus, I think you should add it to this list of good opensource android apps
https://github.com/CHEF-KOCH/Android-Privacy-Data-Protection-Tools-Mega-Thread#networking

Thank you :)

**Comment by FLX-0x00** [comment]
is down now

**Comment by pitsi** [comment]
Lol true. His github account was disabled months ago. 
Now, there is a similar thread about opensource on /r/androidapps. Add it there if you wish
https://old.reddit.com/r/androidapps/comments/jhtvn4/a_list_of_open_source_applications/

**Comment by FLX-0x00** [comment]
Feel free to add this to the list, we archived this project internally - reason:

The whole "functionality" of this app is implemented since android 10 per default in the network manager without the usage of root.

Example source: https://gadgetstouse.com/blog/2020/09/24/know-wifi-password-on-android/
